#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
source_file="$script_dir/../../apps/api/src/db/tinybird/datasources/events.datasource"
generated_dir="$script_dir/generated/datasources"
generated_file="$generated_dir/events.datasource"

if [[ ! -f "$source_file" ]]; then
  printf 'Missing upstream Tinybird datasource: %s\n' "$source_file" >&2
  exit 1
fi

mkdir -p "$generated_dir"
temporary_file="$(mktemp "$generated_dir/events.datasource.tmp.XXXXXX")"
trap 'rm -f "$temporary_file"' EXIT

{
  printf '# Generated from apps/api/src/db/tinybird/datasources/events.datasource.\n'
  printf '# Do not edit this file; run deploy/tinybird/prepare.sh instead.\n\n'
  cat "$source_file"
  printf '\nTOKEN academe_events_ingest APPEND\n'
  printf 'TOKEN academe_events_read READ\n'
} > "$temporary_file"

mv "$temporary_file" "$generated_file"
trap - EXIT
printf 'Generated %s\n' "$generated_file"
